// Russian lang variables utf8

tinyMCE.addToLang('',{
theme_style_select : '-- Стили --',
theme_code_desc : 'Редактировать HTML-код',
theme_code_title : 'Редактор HTML-кода',
theme_code_wordwrap : 'Перенос по словам',
theme_sub_desc : 'Нижний индекс',
theme_sup_desc : 'Верхний индекс',
theme_hr_desc : 'Вставить горизонтальный разделитель',
theme_removeformat_desc : 'Убрать форматирование',
theme_custom1_desc : 'Ваше произвольное описание',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Размеры',
insert_image_vspace : 'Вертикальный отступ',
insert_image_hspace : 'Горизонтальный отступ',
insert_image_align : 'Выравнивание',
insert_image_align_default : '-- Не задано --',
insert_image_align_baseline : 'По базовой линии',
insert_image_align_top : 'По верху',
insert_image_align_middle : 'Посредине',
insert_image_align_bottom : 'По низу',
insert_image_align_texttop : 'По верху текста',
insert_image_align_absmiddle : 'Абсолютно посредине',
insert_image_align_absbottom : 'Абсолютно сверху',
insert_image_align_left : 'Влево',
insert_image_align_right : 'Вправо',
theme_font_size : '-- Разм. шрифта --',
theme_fontdefault : '-- Сем-во шрифта --',
theme_block : '-- Формат --',
theme_paragraph : 'Абзац',
theme_div : 'Div',
theme_address : 'Стиль адреса',
theme_pre : 'Предв. формат.',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_blockquote : 'Цитата',
theme_code : 'Код',
theme_samp : 'Образец кода',
theme_dt : 'Термин ',
theme_dd : 'Определение термина',
theme_colorpicker_title : 'Выбрать цвет',
theme_colorpicker_apply : 'Применить',
theme_forecolor_desc : 'Выбрать цвет текста',
theme_backcolor_desc : 'Выбрать цвет фона',
theme_charmap_title : 'Выбор произвольного символа',
theme_charmap_desc : 'Вставить произвольный символ',
theme_visualaid_desc : 'Показать границы скрытых элементов',
insert_anchor_title : 'Вставить/Изменить якорь',
insert_anchor_name : 'Имя якоря',
theme_anchor_desc : 'Вставить/Изменить якорь',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Копировать/Вырезать/Вставить недоступны для Mozilla и Firefox.\nХотите узнать об этом подробнее?',
theme_path : 'Путь',
cut_desc : 'Вырезать',
copy_desc : 'Копировать',
paste_desc : 'Вставить',
link_list : 'Перечень ссылок',
image_list : 'Перечень изображений',
browse : 'Обзор',
image_props_desc : 'Свойства изображения',
newdocument_desc : 'Новый документ',
class_name : 'Класс',
newdocument : 'Вы уверены, что хотите удалить всё содержимое?',
about_title : 'О программе TinyMCE',
about : 'О программе',
license : 'Лицензия',
plugins : 'Плагины',
plugin : 'Плагин',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Загруженные плагины',
help : 'Помощь',
not_set : '-- Не установлено --',
close : 'Закрыть',
toolbar_focus : 'Переместить фокус на панель инструментов - Alt+Q, Переместить фокус в редактор - Alt-Z, Переместить фокус на элемент пути - Alt-X',
invalid_data : 'Ошибка: Введены некорректные значения, они помечены красным.',
more_colors : 'Другие цвета',
color_picker_tab : 'Выбор',
color_picker : 'Выбор цветов',
web_colors_tab : 'Для веб',
web_colors : 'Цвета для веб',
named_colors_tab : 'Названия',
named_colors : 'Названия цветов',
color : 'Цвет:',
color_name : 'Название:',
is_email : 'Вы ввели адрес электронной почты, добавить к нему префикс mailto: ?',
is_external : 'Вы ввели ссылку на внешний ресурс, добавить к ней префикс http:// ?'
});
